### ISSUE TITLE
"transfer" are only available for objects of type "address payable", not "address".

### ISSUE THREAD

**Issue by Kam0teQ** [PatrickAlphaC/fund_me#19]
Hi, can anyone help me, I was trying on this code but whenever I compile it, remix gives me an error saying TypeError: "send" and "transfer" are only available for objects of type "address payable", not "address". I got this error from the function withdraw() public payable onlyOwner {msg.sender.transfer(address(this).balance;  for(...) }. I just copied and pasted the code from the github repo and change the import for the aggregatorv3interface to import "https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol"; and removed the SafeMath import line. I'm also using compiler version 0.8.7. Thanks in advance. 

<img width="1724" alt="Screen Shot 2022-10-13 at 10 44 12 AM" src="https://user-images.githubusercontent.com/112837124/195668463-f94a9485-383f-4701-8993-eda641f9a167.png">

**Comment by PatrickAlphaC** [comment]
Yep! This was updated in newer versions of solidity. Just make your addresses payable

```
payable(msg.sender).transfer(...);
```

**Comment by Kam0teQ** [comment]
Thanks a lot Patrick! Actually I was also able to make it compile by using: 
uint256 contractBalance = address(this).balance;
payable(msg.sender).transfer(contractBalance);
inside the withdrawal function.
I know this issue is already closed, but could you help on how would I be able to keep up to date with syntax changes such as this in Solidity?
