### ISSUE TITLE
error in withdraw() function

### ISSUE THREAD

**Issue by haisim-y** [PatrickAlphaC/fund_me#2]
Whenever i run this code  msg.sender.transfer(address(this).balance); inside withdraw() function  Remix IDE  is giving an error 
(send and transfer are only available for objects of type "address payable" not address.)
I even copy pasted whole code still getting same error.

**Comment by PatrickAlphaC** [comment]
Can you try compiling with version 0.6.6 ?

**Comment by haisim-y** [comment]
> Can you try compiling with version 0.6.6 ?

Thank You , it worked with version 0.6.6 .  Can u please guide me what will be alternative for withdraw function's code in latest compiler version?

**Comment by ibracn01** [comment]
payable(msg.sender).transfer(address(this).balance);

**Comment by PatrickAlphaC** [comment]
Awesome! Glad that worked. And thanks @ibracn01
