### ISSUE TITLE
Lesson 6 (Brownie FundMe) - FileNotFoundError: Cannot find scripts/deploy.py

### ISSUE THREAD

**Issue by DanielHarbours** [PatrickAlphaC/fund_me#20]
I have managed to compile the contract but when I do to deploy it brownie gives this error:  

FileNotFoundError: Cannot find scripts/deploy.py

Earlier on it says this too:

"/Users/NAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/brownie/project/main.py:743: BrownieEnvironmentWarning: Loaded project has a root folder of '/Users/NAME/demos/brownie_fundme' which is different from the current working directory
  warnings.warn(
BrownieFundmeProject is the active project."

So im guessing the project has a seperate root folder from the CWD. But I cant find how to address this. Can anyone help

**Comment by PatrickAlphaC** [comment]
Can you ask this in the full github? 

https://github.com/smartcontractkit/full-blockchain-solidity-course-py

Thanks!
