### ISSUE TITLE
ParserError: Source file requires different compiler version

### ISSUE THREAD

**Issue by Stmbisa** [PatrickAlphaC/fund_me#21]
I used the same version in the tutorial and here is what error I am facing. I copied the same compiler

**Comment by PatrickAlphaC** [comment]
Could you please make an issue on the full repo? Thanks! https://github.com/smartcontractkit/full-blockchain-solidity-course-py

**Comment by Stmbisa** [comment]
Thanks I have done so

Le lun. 14 nov. 2022 à 20:22, Patrick Collins ***@***.***> a
écrit :
