### ISSUE TITLE
Code Line 86,87 | withraw function

### ISSUE THREAD

**Issue by its-all-relative** [PatrickAlphaC/fund_me#25]
function withdraw() public payable onlyOwner {
        msg.sender.transfer(address(this).balance);

On running this, compiler GPT returns the following - 

```
The error occurred because the `transfer` function is only available for objects of type "address payable", but `msg.sender` is of type "address". To fix the error, you can change the `msg.sender` type to "address payable" by adding the `payable` keyword. 
Here is the corrected code:
```solidity
function withdraw() public {
    address payable recipient = payable(msg.sender);
    recipient.transfer(address(this).balance);
}
By declaring `recipient` as type "address payable" and assigning it the value of `msg.sender`, you can then use `recipient.transfer` to transfer the balance to the sender's address.
```
From 0.8.0 onwards, explicit conversions between literals and the address type result in an address type rather than address payable. The original code should work without needing to cast msg.sender to a payable type. 
However, with compiler set to 0.8.18+ and pragma solidity >= 0.6.6 < 0.9.0, I still see the error. Is there a compilation error or version fix I need to do to make the original code work?

**Comment by PatrickAlphaC** [comment]
If you use compiler version `0.6.6` it should work fine. Could you try that?
