### ISSUE TITLE
 AggregatorV3Interface priceFeed = AggregatorV3Interface(0x8A753747A1Fa494EC906cE90E9f37563A8AF630e);

### ISSUE THREAD

**Issue by veridelisi** [PatrickAlphaC/fund_me#7]
Hi patrick

I dont understand this syntax

There isnt the following formul  in the AggregatorV3Interface.sol

**AggregatorV3Interface(0x8A753747A1Fa494EC906cE90E9f37563A8AF630e);**

https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol

what do you make in this code ?

**AggregatorV3Interface priceFeed = AggregatorV3Interface(0x8A753747A1Fa494EC906cE90E9f37563A8AF630e);**

and 

how can the following code give us version ? This code only include version() function, there no input, where does come from **version output**?

**priceFeed.version()**

Sincerely

**Comment by PatrickAlphaC** [comment]
In the interface, you'll see [the version function](https://github.com/smartcontractkit/chainlink/blob/0ee42023dc58a7b354c0a93bfe5a4f931c2175e3/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol#L20).

With this, we are saying, at address `0x8A753747A1Fa494EC906cE90E9f37563A8AF630e`, their is a function called `version` that we can call.

The interface just tells us the functions that we can interact with, but the funciton details itself are in another contract and deployed on chain.

Does that make sense?

**Comment by veridelisi** [comment]
but the funciton details itself are in another contract ? Which contract ?

**Comment by PatrickAlphaC** [comment]
Yes! They are in the contract at the address specified. For example, we can see a price feed deployed here: https://etherscan.io/address/0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419#readContract

Inside the code, it actually is a proxy pointing to https://etherscan.io/address/0x37bc7498f4ff12c19678ee8fe19d713b87f6a9e6#readContract

Where we can read the code implementations of those funcitons.
