### ISSUE TITLE
Remove getConversionRate() in require statement for FundMe.sol

### ISSUE THREAD

**Issue by MatHatter** [PatrickAlphaC/fund_me#9]
Hi,

I was having problems debugging this section as it seems like `getConversionRate()` does not need to be in the 'require()' statement; line 21. My code was not acting the same, as in, MetaMask was not opening up immediately after I clicked fund for values that were greater than or equal to the minimumUSD. At time 3:06:36, my Metamask still pops up when my eth is lower than the minimum, but when I remove the `getConversionRate()` it works properly. With `getConversionRate()` in the logical statement, minimumUSD is comparing to nothing really it seems so that line is not really doing anything, then it goes to the next line.

This will help you understand exactly what I am talking about:

I did different values and after I deployed and tried 4000000000000000 wei for the fund button it still worked (lower values like 0, 10, 50000 worked as in the gas error came up with the string).  Only values of 5000000000000000 or higher for the fund button should work (after deploying with 0), and this only worked properly when I took out `getConversionRate()`.
```
function fund() public payable {

        uint256 minimumUSD = 5 * 10 ** 15;
        require(getConversionRate(msg.value) >= minimumUSD, "You need to spend more ETH!");
        addressToAmountFunded[msg.sender] += msg.value;
    }
```

working code with values like 4000000000000000 wei (as in MetaMask should not come up.)

```
function fund() public payable {

        uint256 minimumUSD = 5 * 10 ** 15;
        require(msg.value >= minimumUSD, "You need to spend more ETH!");
        addressToAmountFunded[msg.sender] += msg.value;
    }
```

**Comment by PatrickAlphaC** [comment]
I'm not sure I follow.

It sounds like this is working as intended, except your minimumUSD should be `uint256 minimumUSD = 50 * 10 ** 18;`. 

We are looking to make the payment of this fund method be $50 in ETH. So you need to send $50 worth of ETH to the contract. The require statement makes sure that happens. 

Let me know if that's not clear.

**Comment by MatHatter** [comment]
If you actually try what I am talking about, you would run into the same problem. I brought down the eth because eth's value is higher now. I agree, we need need the require statement, but what is `getConversionRate()` in the require code?

**Comment by MatHatter** [comment]
10 ** 18 versus 10 ** 15 is beside the fact.

Also, I think it makes more sense to have the variable weiAmount instead of ethAmount.

Anyways, thanks for the course! I love it!

**Comment by MatHatter** [comment]
Ok, I see where I was having the issue now. `getConversionRate()` does need to be in the code. I think I was running into problems because `5 * 10 ** 18` is 5 ETH and 5 * ~$2,111 at the time of the video is around $10,000 and we just want $50, so I think that needs to be adjusted. Hence, I was having problems working with low amounts of ETH in Test. The Rinkeby website is not working properly so I can only get around 0.1 ETH at a time.
